/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table states
# ------------------------------------------------------------

DROP TABLE IF EXISTS `states`;

CREATE TABLE `states` (
  `id` int(2) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `active` int(1) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOCK TABLES `states` WRITE;
/*!40000 ALTER TABLE `states` DISABLE KEYS */;

INSERT INTO `states` (`id`, `name`, `active`)
VALUES
	(5,'ANTIOQUIA',1),
	(8,'ATLÁNTICO',1),
	(11,'BOGOTÁ, D.C.',1),
	(13,'BOLÍVAR',1),
	(15,'BOYACÁ',1),
	(17,'CALDAS',1),
	(18,'CAQUETÁ',1),
	(19,'CAUCA',1),
	(20,'CESAR',1),
	(23,'CÓRDOBA',1),
	(25,'CUNDINAMARCA',1),
	(27,'CHOCÓ',1),
	(41,'HUILA',1),
	(44,'LA GUAJIRA',1),
	(47,'MAGDALENA',1),
	(50,'META',1),
	(52,'NARIÑO',1),
	(54,'NORTE DE SANTANDER',1),
	(63,'QUINDIO',1),
	(66,'RISARALDA',1),
	(68,'SANTANDER',1),
	(70,'SUCRE',1),
	(73,'TOLIMA',1),
	(76,'VALLE DEL CAUCA',1),
	(81,'ARAUCA',1),
	(85,'CASANARE',1),
	(86,'PUTUMAYO',1),
	(88,'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',1),
	(91,'AMAZONAS',1),
	(94,'GUAINÍA',1),
	(95,'GUAVIARE',1),
	(97,'VAUPÉS',1),
	(99,'VICHADA',1);

/*!40000 ALTER TABLE `states` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;